spring:
  redis:
#    host: ${redis.host:localhost}
#    port: ${redis.port:6379}
#    password: "123456"
    cluster:
      nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005

stomp-redis-relay:
  channel-prefix: '/'

logging.level.me.itzg.stomprelay: TRACE

